config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "heavy_tasks#index"
  resources :heavy_tasks, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/heavy_tasks_controller.rb
class HeavyTasksController < ApplicationController
  def index; end
  
  def create
    HeavyTaskJob.perform_later
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heavy_tasks_helper.rb
module HeavyTasksHelper
end

app/views/heavy_tasks/_button.html.erb
<%= turbo_stream_from(["heavy_task_channel"]) %>

<div id="heavy_task">
  <%= button_to("Perform Heavy Task", heavy_tasks_path, class: "") %>
</div>

app/views/heavy_tasks/_progress.html.erb
<div id="heavy_task">
  <div class="progress-bar">
    <div class="progress-bar-inner" role="progressbar" style="width: <%= progress %>%;">
    </div>
  </div>
</div>

app/views/heavy_tasks/index.html.erb
<style>
  .progress-bar {
    width: 300px;
    height: 20px;
    background-color: #f0f0f0;
    border-radius: 10px;
    overflow: hidden;
  }
  
  .progress-bar-inner {
    height: 100%;
    background-color: #4CAF50;
    transition: width 0.5s ease-in-out;
  }
</style>

<h1>Seamless Progress</h1>
<p>Here we'll show the progress bars of background jobs</p>

<%= render(partial: "button") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BroadcastingProgressFromBackgroundJobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>